# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名称')),
                ('img', models.CharField(max_length=255, verbose_name='图片链接')),
                ('url', models.CharField(max_length=255, verbose_name='跳转链接')),
                ('pri', models.IntegerField(default=0, help_text='数字越小，优先级越高', verbose_name='优先级')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ('pri',),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='店面名称')),
                ('tag', models.CharField(blank=True, max_length=128, null=True, verbose_name='标签')),
                ('pri', models.IntegerField(default=0, help_text='数字越小，优先级越高', verbose_name='优先级')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='详细描述')),
            ],
            options={
                'verbose_name': '店面',
                'verbose_name_plural': '店面',
                'ordering': ('pri',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Type', verbose_name='类型'),
        ),
    ]
